"""Shared Pydantic models for orders."""

from typing import List, Optional

from pydantic import BaseModel, Field


class OrderBase(BaseModel):
    """Shared fields for an order."""

    order_number: str = Field(..., description="Order identifier (e.g. #ORD1001)")
    customer_name: str = Field(..., description="Name of the customer")
    order_date: str = Field(..., description="Date of the order in YYYY-MM-DD format")
    status: str = Field(..., description="Current status (Pending, Completed, Refunded)")
    total_amount: float = Field(..., description="Total price")
    payment_status: str = Field(..., description="Payment state (Paid, Unpaid)")


class OrderCreate(OrderBase):
    """Schema for creating a new order."""


class OrderUpdate(BaseModel):
    """Schema for updating an existing order. All fields are optional."""

    order_number: Optional[str] = Field(None)
    customer_name: Optional[str] = Field(None)
    order_date: Optional[str] = Field(None)
    status: Optional[str] = Field(None)
    total_amount: Optional[float] = Field(None)
    payment_status: Optional[str] = Field(None)


class OrderResponse(OrderBase):
    """Response schema including the autogenerated primary key."""

    id: int


class BulkStatusUpdate(BaseModel):
    """Request body for bulk status update."""

    order_ids: List[int] = Field(..., description="IDs to update")
    status: str = Field(..., description="New status")


class BulkIds(BaseModel):
    """Request body for operations that only need a list of IDs."""

    order_ids: List[int] = Field(..., description="IDs to operate on")
